version = 1
test_patterns = ["test/**"]
exclude_patterns = ["node_modules/*"]
[[analyzers]]
name = "javascript"
enabled = true
 [analyzers.meta]
 environment = [
  "nodejs",
  "mocha"
 ]
 style_guide = "standard"
[[transformers]]
name = "standardjs"
enabled = true
